name: Start Linux VPS and Setup RustDesk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install RustDesk on GitHub-hosted runner
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://rustdesk.com/install.sh | sh
        sudo systemctl enable rustdesk && sudo systemctl start rustdesk
      env:
        RUSTDESK_ID: ${{ secrets.1346983981 }}
        RUSTDESK_PASSWORD: ${{ secrets.Disalardp1 }}
